"""
GitHub Service — creates branches, commits ACTUAL Terraform files, and opens Pull Requests.
Uses PyGithub.

CRITICAL BEHAVIOUR:
  - Existing source systems: reads terraform/{source_system}/locals.tf from the repo,
    inserts the new HCL job entry into the glue_jobs = { ... } map, and commits the
    modified file.  The glue.tf is NOT touched — its for_each picks up new entries.
  - New source systems: creates terraform/{source_system}/locals.tf from
    state.locals_tf_full and terraform/{source_system}/glue.tf from state.glue_tf_content.

PR creation only happens after explicit user approval.
"""

import re
import time
import logging
from datetime import datetime
from github import Github, GithubException
from app.config import get_settings

logger = logging.getLogger(__name__)


# ── Simple retry with exponential backoff (no external dependency) ────────────

def _with_retry(fn, max_attempts: int = 3, delay: float = 1.0, backoff: float = 2.0):
    """
    Call fn() up to max_attempts times, sleeping delay*(backoff**attempt) between
    retries.  Auth errors (401/403) and not-found (404) are re-raised immediately.
    """
    attempt = 0
    current_delay = delay
    while True:
        try:
            return fn()
        except GithubException as exc:
            attempt += 1
            # Never retry permanent errors
            if attempt >= max_attempts or exc.status in (401, 403, 404):
                raise
            logger.warning(
                "GitHub API call failed (attempt %d/%d, status %s): %s — retrying in %.1fs",
                attempt, max_attempts, exc.status, exc.data, current_delay,
            )
            time.sleep(current_delay)
            current_delay *= backoff


# ── HCL insertion helper ──────────────────────────────────────────────────────

def _insert_into_glue_jobs(locals_tf_content: str, new_entry_hcl: str) -> str:
    """
    Insert *new_entry_hcl* into the ``glue_jobs = { ... }`` block inside locals.tf.

    Strategy:
      1. Find the ``glue_jobs = {`` line with a regex (tolerates whitespace variants).
      2. Track brace depth from the opening brace to locate the exact matching ``}``.
      3. Insert the trimmed entry + trailing newline immediately before that ``}``.

    Args:
        locals_tf_content: Full text of the existing locals.tf file.
        new_entry_hcl:     The job entry block to add (already indented at 2 spaces).

    Returns:
        Modified file content (string).

    Raises:
        ValueError: If the glue_jobs block cannot be found or braces are unmatched.
    """
    # Normalise line endings
    content = locals_tf_content.replace("\r\n", "\n")

    # Find the glue_jobs opening — handles whitespace variants
    pattern = re.compile(r"(\s*glue_jobs\s*=\s*\{)")
    match = pattern.search(content)
    if not match:
        raise ValueError(
            "Could not find 'glue_jobs = {' block in locals.tf. "
            "Ensure the file follows the expected structure with a top-level "
            "glue_jobs = { ... } map."
        )

    open_pos = match.end()   # position *after* the opening {

    # Track brace depth to locate the matching closing }
    depth = 1
    pos = open_pos
    while pos < len(content) and depth > 0:
        ch = content[pos]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
        pos += 1

    if depth != 0:
        raise ValueError(
            "Unmatched braces in glue_jobs block — cannot safely insert entry. "
            "Please verify the locals.tf file is syntactically correct HCL."
        )

    close_brace_pos = pos - 1   # index of the closing }

    # Prepare the entry string
    entry = new_entry_hcl.strip("\n")
    if not entry.endswith("\n"):
        entry += "\n"

    # Decide separator: blank line if the block already has content
    inner = content[open_pos:close_brace_pos].strip()
    separator = "\n\n" if inner else "\n"

    before = content[:close_brace_pos]
    after  = content[close_brace_pos:]   # starts with '}'

    return before + separator + entry + "\n" + after


# ── Service class ─────────────────────────────────────────────────────────────

class GitHubService:
    """
    Wraps PyGithub to create branches, commit Terraform files, and open PRs.

    For EXISTING source systems: reads the actual ``terraform/{source}/locals.tf``,
    inserts the new job entry, and commits the modified file.

    For NEW source systems: creates both ``locals.tf`` and ``glue.tf`` from scratch
    using the content generated by TerraformAgent.
    """

    def __init__(self):
        settings = get_settings()
        self._gh           = Github(settings.github_token.get_secret_value())
        self._repo_owner   = settings.github_repo_owner
        self._repo_name    = settings.github_repo_name
        self._base_branch  = settings.github_base_branch
        # Optional reviewer list (comma-separated GitHub usernames)
        raw = settings.github_pr_reviewers or ""
        self._reviewers = [r.strip() for r in raw.split(",") if r.strip()]

    def _get_repo(self):
        return _with_retry(
            lambda: self._gh.get_repo(f"{self._repo_owner}/{self._repo_name}")
        )

    def get_source_system_repository_state(self, source_system: str) -> dict:
        """
        Resolve source-system existence from the live GitHub repository.

        GitHub is the authoritative source of truth. A source system exists only if
        ``terraform/{source_system}/locals.tf`` exists on the configured base branch.
        """
        repo = self._get_repo()
        locals_path = f"terraform/{source_system}/locals.tf"
        github_exists = self._get_file_content(repo, locals_path, self._base_branch) is not None

        logger.info(
            "GitHub source-system check: source_system=%s base_branch=%s path=%s github_exists=%s",
            source_system,
            self._base_branch,
            locals_path,
            github_exists,
        )

        return {
            "source_system": source_system,
            "base_branch": self._base_branch,
            "locals_path": locals_path,
            "github_exists": github_exists,
        }

    def make_branch_name(self, source_system: str, schema_grain: str) -> str:
        """Branch naming: feature/glue-job-{source_system}-{schema_grain}-{timestamp}"""
        ts       = datetime.utcnow().strftime("%Y%m%d%H%M%S")
        safe_ss  = re.sub(r"[^a-z0-9-]", "-", source_system.lower())
        safe_sg  = re.sub(r"[^a-z0-9-]", "-", schema_grain.lower())
        return f"feature/glue-job-{safe_ss}-{safe_sg}-{ts}"

    # ── Public entry point ────────────────────────────────────────────────────

    def create_pr(self, state: dict) -> dict:
        """
        Create a GitHub PR with **actual Terraform file changes**.

        *** CRITICAL: GitHub repository is the authoritative source of truth ***
        Before deciding between existing vs new source system workflow, this method
        checks the actual GitHub repository for terraform/{source}/locals.tf.
        The workflow state 'source_system_exists' flag is OVERRIDDEN by the real repo state.

        For existing source systems:
          * Reads ``terraform/{source}/locals.tf`` from the base branch.
          * Inserts the new job entry into the ``glue_jobs`` map.
          * Commits the modified file.

        For new source systems:
          * Creates ``terraform/{source}/locals.tf`` (full file from state).
          * Creates ``terraform/{source}/glue.tf`` (standard module block).

        Returns:
            dict with keys: pr_url, branch_name, pr_number, files_modified
        """
        if not state.get("user_approved"):
            raise ValueError("PR creation attempted without user approval")

        repo           = self._get_repo()
        source_system  = state.get("source_system", "")
        schema_grain   = state.get("schema_grain", "")
        branch_name    = state.get("branch_name") or self.make_branch_name(source_system, schema_grain)
        
        # ──────────────────────────────────────────────────────────────────────
        # CRITICAL FIX: Check GitHub repository to determine if source exists
        # This is the SOURCE OF TRUTH — not knowledge base, not workflow state
        # ──────────────────────────────────────────────────────────────────────
        repo_state = self.get_source_system_repository_state(source_system)
        locals_path_in_repo = repo_state["locals_path"]
        actual_file_exists = repo_state["github_exists"]
        
        # The GitHub repository state is authoritative
        source_exists = actual_file_exists
        
        # Log the decision for debugging
        workflow_state_claim = state.get("source_system_exists", True)
        if workflow_state_claim != source_exists:
            logger.info(
                "REPOSITORY STATE OVERRIDE: workflow claimed source_system_exists=%s, "
                "but GitHub shows %s (file=%s). Using GitHub state as source of truth.",
                workflow_state_claim, source_exists, locals_path_in_repo
            )
        else:
            logger.info(
                "Repository state matches workflow state: source_system_exists=%s "
                "(GitHub: %s exists)", source_exists, "does" if source_exists else "does not"
            )
        job_key        = state.get("job_key", "unknown")
        environment    = state.get("environment", "")

        # ── 1. Get base SHA and create branch ────────────────────────────────
        base_ref = _with_retry(lambda: repo.get_branch(self._base_branch))
        base_sha = base_ref.commit.sha

        try:
            _with_retry(
                lambda: repo.create_git_ref(
                    ref=f"refs/heads/{branch_name}", sha=base_sha
                )
            )
        except GithubException as exc:
            if exc.status == 422:
                logger.info("Branch '%s' already exists — continuing.", branch_name)
            else:
                raise

        # ── 2. Commit Terraform files ─────────────────────────────────────────
        committed_files: list[str] = []
        if source_exists:
            committed_files.extend(self._commit_existing_system(repo, branch_name, state))
        else:
            committed_files.extend(self._commit_new_system(repo, branch_name, state))

        # ── 3. Open Pull Request ──────────────────────────────────────────────
        pr_title = f"feat(glue): Add Glue job {job_key}"
        # Pass the actual source_exists value (from GitHub check, not from state)
        pr_body  = self._build_pr_body(state, committed_files, source_exists_actual=source_exists)

        pr = _with_retry(
            lambda: repo.create_pull(
                title=pr_title,
                body=pr_body,
                head=branch_name,
                base=self._base_branch,
            )
        )

        # ── 4. Labels (fail gracefully — labels may not exist in repo yet) ───
        try:
            labels = ["ai-generated", "terraform"]
            if environment:
                labels.append(f"env:{environment}")
            pr.add_to_labels(*labels)
        except GithubException as exc:
            logger.warning("Could not add labels to PR #%s: %s", pr.number, exc)

        # ── 5. Reviewers (fail gracefully) ────────────────────────────────────
        if self._reviewers:
            try:
                pr.create_review_request(reviewers=self._reviewers)
            except GithubException as exc:
                logger.warning(
                    "Could not assign reviewers to PR #%s: %s", pr.number, exc
                )

        return {
            "pr_url":        pr.html_url,
            "branch_name":   branch_name,
            "pr_number":     pr.number,
            "files_modified": committed_files,
        }

    # ── Scenario 1: existing source system ────────────────────────────────────

    def _commit_existing_system(
        self, repo, branch_name: str, state: dict
    ) -> list[str]:
        """
        Read ``terraform/{source}/locals.tf`` from the base branch, insert the new
        job entry into the ``glue_jobs`` block, and commit the modified file to the
        PR branch.  glue.tf is NOT modified — its for_each handles new entries.
        """
        source_system = state.get("source_system", "")
        job_key       = state.get("job_key", "unknown")
        terraform_hcl = state.get("terraform_hcl", "")

        if not terraform_hcl:
            raise ValueError("state.terraform_hcl is empty — cannot insert job entry")

        locals_path = f"terraform/{source_system}/locals.tf"

        # Read from base branch (authoritative content)
        base_file = self._get_file_content(repo, locals_path, self._base_branch)
        if base_file is None:
            raise ValueError(
                f"Could not read '{locals_path}' from branch '{self._base_branch}'. "
                "Verify the file exists in the repository and the branch name is correct."
            )

        current_content = base_file.decoded_content.decode("utf-8")

        # Insert the new job entry
        try:
            modified_content = _insert_into_glue_jobs(current_content, terraform_hcl)
        except ValueError as exc:
            raise ValueError(
                f"Failed to insert job entry into {locals_path}: {exc}\n\n"
                f"HCL block to insert:\n{terraform_hcl}"
            ) from exc

        commit_message = f"feat(glue): add {job_key} to {locals_path}"

        # Commit to PR branch (create if not present, update if branch already had a commit)
        self._create_or_update_file(
            repo, locals_path, modified_content, commit_message, branch_name
        )
        return [locals_path]

    # ── Scenario 2: new source system ─────────────────────────────────────────

    def _commit_new_system(
        self, repo, branch_name: str, state: dict
    ) -> list[str]:
        """
        Create ``terraform/{source}/locals.tf`` and ``terraform/{source}/glue.tf``
        from scratch using the content generated by TerraformAgent.
        """
        source_system   = state.get("source_system", "")
        job_key         = state.get("job_key", "unknown")
        locals_tf_full  = state.get("locals_tf_full", "")
        glue_tf_content = state.get("glue_tf_content", "")

        if not locals_tf_full:
            raise ValueError(
                "state.locals_tf_full is empty — cannot create locals.tf for new "
                "source system. Ensure the generate_terraform step ran successfully."
            )

        committed: list[str] = []
        locals_path = f"terraform/{source_system}/locals.tf"
        glue_path   = f"terraform/{source_system}/glue.tf"

        self._create_or_update_file(
            repo, locals_path, locals_tf_full,
            f"feat(glue): create {locals_path} for {job_key}",
            branch_name,
        )
        committed.append(locals_path)

        if glue_tf_content:
            self._create_or_update_file(
                repo, glue_path, glue_tf_content,
                f"feat(glue): create {glue_path} (standard module block)",
                branch_name,
            )
            committed.append(glue_path)

        return committed

    # ── File helpers ──────────────────────────────────────────────────────────

    def _create_or_update_file(
        self,
        repo,
        path: str,
        content: str,
        message: str,
        branch: str,
    ) -> None:
        """Create or update a single file on the given branch."""
        existing = self._get_file_content(repo, path, branch)
        if existing:
            _with_retry(
                lambda: repo.update_file(
                    path=path,
                    message=message,
                    content=content,
                    sha=existing.sha,
                    branch=branch,
                )
            )
        else:
            _with_retry(
                lambda: repo.create_file(
                    path=path,
                    message=message,
                    content=content,
                    branch=branch,
                )
            )

    def _get_file_content(self, repo, path: str, branch: str):
        """Return the ContentFile object for *path* on *branch*, or None."""
        try:
            return repo.get_contents(path, ref=branch)
        except GithubException:
            return None

    # ── PR body ───────────────────────────────────────────────────────────────

    def _build_pr_body(self, state: dict, committed_files: list[str], source_exists_actual: bool = None) -> str:
        """Compose a detailed PR description including the generated HCL.
        
        Args:
            source_exists_actual: If provided, use this value instead of state's source_system_exists.
                                 This represents the ACTUAL GitHub repository state.
        """
        job_key        = state.get("job_key", "")
        topic          = state.get("topic", "")
        source_system  = state.get("source_system", "")
        schema_grain   = state.get("schema_grain", "")
        # Use actual GitHub state if provided, otherwise fall back to state
        source_exists  = source_exists_actual if source_exists_actual is not None else state.get("source_system_exists", True)
        worker_type    = state.get("worker_type", "G.1X")
        num_workers    = state.get("number_of_workers", 2)
        environment    = state.get("environment", "")
        terraform_hcl  = state.get("terraform_hcl", "")

        status_badge = (
            "✅ Existing source system"
            if source_exists
            else "⚠️ **New source system** — folder and both Terraform files created"
        )
        files_md = "\n".join(f"- `{f}`" for f in committed_files)

        return f"""## 🚀 New Glue Job: `{job_key}`

> **Created by:** MIF Glue Job Agent (AI-assisted Terraform generation)

| Field | Value |
|---|---|
| Kafka Topic | `{topic}` |
| Environment | `{environment}` |
| Source System | `{source_system}` — {status_badge} |
| Schema Grain | `{schema_grain}` |
| Workers | {num_workers} × {worker_type} |

### Files Modified

{files_md}

### Generated HCL

```hcl
{terraform_hcl}
```

---

> ⚠️ **Terraform Plan Required** — please run `terraform plan` in the affected \
directory before merging.
> This PR was auto-generated by the MIF Glue Job Agent. Review the HCL carefully \
before approving.
"""


