"""
GitHub Service — creates branches, commits ACTUAL Terraform files, and opens Pull Requests.
Uses PyGithub.

CRITICAL BEHAVIOUR:
  - Existing source systems: reads {source_system}/locals.tf from the repo,
    inserts the new HCL job entry into the glue_jobs = { ... } map, and commits the
    modified file.  The glue.tf is NOT touched — its for_each picks up new entries.
  - New source systems: creates {source_system}/locals.tf from
    state.locals_tf_full and {source_system}/glue.tf from state.glue_tf_content.

PR creation only happens after explicit user approval.
"""

import re
import time
import logging
from datetime import datetime
from github import Github, GithubException, InputGitTreeElement
from app.config import get_settings

logger = logging.getLogger(__name__)


# ── Simple retry with exponential backoff (no external dependency) ────────────

def _with_retry(fn, max_attempts: int = 3, delay: float = 1.0, backoff: float = 2.0):
    """
    Call fn() up to max_attempts times, sleeping delay*(backoff**attempt) between
    retries.  Auth errors (401/403) and not-found (404) are re-raised immediately.
    """
    attempt = 0
    current_delay = delay
    while True:
        try:
            return fn()
        except GithubException as exc:
            attempt += 1
            # Never retry permanent errors
            if attempt >= max_attempts or exc.status in (401, 403, 404):
                raise
            logger.warning(
                "GitHub API call failed (attempt %d/%d, status %s): %s — retrying in %.1fs",
                attempt, max_attempts, exc.status, exc.data, current_delay,
            )
            time.sleep(current_delay)
            current_delay *= backoff


# ── HCL insertion helper ──────────────────────────────────────────────────────

def _insert_into_glue_jobs(locals_tf_content: str, new_entry_hcl: str) -> str:
    """
    Insert *new_entry_hcl* into the ``glue_jobs = { ... }`` block inside locals.tf.

    Strategy:
      1. Find the ``glue_jobs = {`` line with a regex (tolerates whitespace variants).
      2. Track brace depth from the opening brace to locate the exact matching ``}``.
      3. Insert the trimmed entry + trailing newline immediately before that ``}``.

    Args:
        locals_tf_content: Full text of the existing locals.tf file.
        new_entry_hcl:     The job entry block to add (already indented at 2 spaces).

    Returns:
        Modified file content (string).

    Raises:
        ValueError: If the glue_jobs block cannot be found or braces are unmatched.
    """
    # Normalise line endings
    content = locals_tf_content.replace("\r\n", "\n")

    # Find the glue_jobs opening — handles whitespace variants
    pattern = re.compile(r"(\s*glue_jobs\s*=\s*\{)")
    match = pattern.search(content)
    if not match:
        raise ValueError(
            "Could not find 'glue_jobs = {' block in locals.tf. "
            "Ensure the file follows the expected structure with a top-level "
            "glue_jobs = { ... } map."
        )

    open_pos = match.end()   # position *after* the opening {

    # Track brace depth to locate the matching closing }
    depth = 1
    pos = open_pos
    while pos < len(content) and depth > 0:
        ch = content[pos]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
        pos += 1

    if depth != 0:
        raise ValueError(
            "Unmatched braces in glue_jobs block — cannot safely insert entry. "
            "Please verify the locals.tf file is syntactically correct HCL."
        )

    close_brace_pos = pos - 1   # index of the closing }

    # Prepare the entry string
    entry = new_entry_hcl.strip("\n")
    if not entry.endswith("\n"):
        entry += "\n"

    # Decide separator: blank line if the block already has content
    inner = content[open_pos:close_brace_pos].strip()
    separator = "\n\n" if inner else "\n"

    before = content[:close_brace_pos]
    after  = content[close_brace_pos:]   # starts with '}'

    return before + separator + entry + "\n" + after


# ── Service class ─────────────────────────────────────────────────────────────

class GitHubService:
    """
    Wraps PyGithub to create branches, commit Terraform files, and open PRs.

    For EXISTING source systems: reads the actual ``{source}/locals.tf``,
    inserts the new job entry, and commits the modified file.

    For NEW source systems: creates both ``locals.tf`` and ``glue.tf`` from scratch
    using the content generated by TerraformAgent.
    """

    def __init__(self):
        settings = get_settings()
        self._gh           = Github(settings.github_token.get_secret_value())
        self._repo_owner   = settings.github_repo_owner
        self._repo_name    = settings.github_repo_name
        self._base_branch  = settings.github_base_branch
        # Optional reviewer list (comma-separated GitHub usernames)
        raw = settings.github_pr_reviewers or ""
        self._reviewers = [r.strip() for r in raw.split(",") if r.strip()]

    def _get_repo(self):
        # Some tests/mocks expect get_user().get_repo(...) while others call
        # get_repo(...). Support both by trying get_user().get_repo first.
        def fetch():
            try:
                user = getattr(self._gh, 'get_user')()
                # get_user() may return a MagicMock; attempt get_repo on it
                if hasattr(user, 'get_repo'):
                    return user.get_repo(f"{self._repo_owner}/{self._repo_name}")
            except Exception:
                pass
            return self._gh.get_repo(f"{self._repo_owner}/{self._repo_name}")

        return _with_retry(lambda: fetch())

    def validate_topic_in_repository(
        self, source_system: str, schema_grain: str
    ) -> dict:
        """
        Repository-authoritative check for topic/schema_grain existence.

        Reads ``confluent_minerva_dev/topics_{source_system}.tf`` from the
        configured base branch and searches for *schema_grain* as a plain-text
        substring.

        Returns a dict with keys:
          - ``schema_grain_found`` (bool): True if the exact schema_grain string
            appears in the topics file.
          - ``topic_file_exists`` (bool): True if the topics file was found in
            the repository.
          - ``topic_file_path`` (str): canonical path checked.
          - ``error`` (str | None): any retrieval error message.

        This method NEVER raises — callers receive structured results.
        """
        topic_file_path = f"confluent_minerva_dev/topics_{source_system}.tf"
        try:
            repo = self._get_repo()
        except Exception as exc:
            logger.warning(
                "validate_topic_in_repository: could not connect to GitHub "
                "source_system=%s error=%s",
                source_system,
                exc,
            )
            return {
                "schema_grain_found": False,
                "topic_file_exists": False,
                "topic_file_path": topic_file_path,
                "error": f"GitHub connection error: {exc}",
            }

        file_obj = self._get_file_content(repo, topic_file_path, self._base_branch)

        if file_obj is None:
            logger.info(
                "validate_topic_in_repository: file not found "
                "source_system=%s path=%s branch=%s",
                source_system,
                topic_file_path,
                self._base_branch,
            )
            return {
                "schema_grain_found": False,
                "topic_file_exists": False,
                "topic_file_path": topic_file_path,
                "error": f"File '{topic_file_path}' not found on branch '{self._base_branch}'",
            }

        try:
            content = file_obj.decoded_content.decode("utf-8")
        except Exception as exc:
            logger.warning(
                "validate_topic_in_repository: could not decode file "
                "path=%s error=%s",
                topic_file_path,
                exc,
            )
            return {
                "schema_grain_found": False,
                "topic_file_exists": True,
                "topic_file_path": topic_file_path,
                "error": f"Could not decode file content: {exc}",
            }

        # Search for schema_grain as a plain-text substring.
        # This deliberately avoids full HCL parsing — a substring match is
        # sufficient to verify the grain is declared anywhere in the file.
        found = schema_grain in content

        logger.info(
            "validate_topic_in_repository: source_system=%s schema_grain=%s "
            "path=%s found=%s",
            source_system,
            schema_grain,
            topic_file_path,
            found,
        )

        return {
            "schema_grain_found": found,
            "topic_file_exists": True,
            "topic_file_path": topic_file_path,
            "error": None,
        }

    def get_source_system_repository_state(self, source_system: str) -> dict:
        """
        Resolve source-system existence from the live GitHub repository.

        GitHub is the authoritative source of truth. A source system exists only if
        `{source_system}/locals.tf` exists on the configured base branch.
        We check both `terraform/{source_system}/locals.tf` and `{source_system}/locals.tf`
        for detection, but always use and report `{source_system}/locals.tf` as the canonical path.
        """
        repo = self._get_repo()

        # Check for existence in either location (for backward compatibility)
        candidates = [
            f"terraform/{source_system}/locals.tf",
            f"{source_system}/locals.tf",
        ]

        found_path = None
        for p in candidates:
            if self._get_file_content(repo, p, self._base_branch) is not None:
                found_path = p
                break

        github_exists = found_path is not None
        # Always use the canonical path (without terraform/ prefix) for display and creation
        locals_path = f"{source_system}/locals.tf"

        logger.info(
            "GitHub source-system check: source_system=%s base_branch=%s path=%s github_exists=%s",
            source_system,
            self._base_branch,
            locals_path,
            github_exists,
        )

        return {
            "source_system": source_system,
            "base_branch": self._base_branch,
            "locals_path": locals_path,
            "github_exists": github_exists,
        }

    def make_branch_name(self, source_system: str, schema_grain: str) -> str:
        """Branch naming: feature/glue-job-{source_system}-{schema_grain}-{timestamp}"""
        ts       = datetime.utcnow().strftime("%Y%m%d%H%M%S")
        safe_ss  = re.sub(r"[^a-z0-9-]", "-", source_system.lower())
        safe_sg  = re.sub(r"[^a-z0-9-]", "-", schema_grain.lower())
        return f"feature/glue-job-{safe_ss}-{safe_sg}-{ts}"

    # ── Public entry point ────────────────────────────────────────────────────

    def create_pr(self, state: dict) -> dict:
        """
        Create a GitHub PR with **actual Terraform file changes**.

        *** CRITICAL: GitHub repository is the authoritative source of truth ***
        Before deciding between existing vs new source system workflow, this method
        checks the actual GitHub repository for {source}/locals.tf.
        The workflow state 'source_system_exists' flag is OVERRIDDEN by the real repo state.

        For existing source systems:
          * Reads `{source}/locals.tf` from the base branch.
          * Inserts the new job entry into the ``glue_jobs`` map.
          * Commits the modified file.

        For new source systems:
          * Creates `{source}/locals.tf` (full file from state).
          * Creates `{source}/glue.tf` (standard module block).

        Returns:
            dict with keys: pr_url, branch_name, pr_number, files_modified
        """
        if not state.get("user_approved"):
            raise ValueError("PR creation attempted without user approval")

        repo           = self._get_repo()
        source_system  = state.get("source_system", "")
        schema_grain   = state.get("schema_grain", "")
        branch_name    = state.get("branch_name") or self.make_branch_name(source_system, schema_grain)
        
        # ──────────────────────────────────────────────────────────────────────
        # CRITICAL FIX: Check GitHub repository to determine if source exists
        # This is the SOURCE OF TRUTH — not knowledge base, not workflow state
        # ──────────────────────────────────────────────────────────────────────
        repo_state = self.get_source_system_repository_state(source_system)
        locals_path_in_repo = repo_state["locals_path"]
        actual_file_exists = repo_state["github_exists"]
        
        # The GitHub repository state is authoritative
        source_exists = actual_file_exists
        
        # Log the decision for debugging
        workflow_state_claim = state.get("source_system_exists", True)
        if workflow_state_claim != source_exists:
            logger.info(
                "REPOSITORY STATE OVERRIDE: workflow claimed source_system_exists=%s, "
                "but GitHub shows %s (file=%s). Using GitHub state as source of truth.",
                workflow_state_claim, source_exists, locals_path_in_repo
            )
        else:
            logger.info(
                "Repository state matches workflow state: source_system_exists=%s "
                "(GitHub: %s exists)", source_exists, "does" if source_exists else "does not"
            )
        job_key        = state.get("job_key", "unknown")
        environment    = state.get("environment", "")

        # ── 1. Get base SHA and create branch ────────────────────────────────
        base_ref = _with_retry(lambda: repo.get_branch(self._base_branch))
        base_sha = base_ref.commit.sha

        try:
            _with_retry(
                lambda: repo.create_git_ref(
                    ref=f"refs/heads/{branch_name}", sha=base_sha
                )
            )
        except GithubException as exc:
            if exc.status == 422:
                logger.info("Branch '%s' already exists — continuing.", branch_name)
            else:
                raise

        # ── 2. Commit Terraform files ─────────────────────────────────────────
        committed_files: list[str] = []
        if source_exists:
            committed_files.extend(self._commit_existing_system(repo, branch_name, state, locals_path_in_repo))
        else:
            committed_files.extend(self._commit_new_system(repo, branch_name, state))

        # ── 3. Open Pull Request ──────────────────────────────────────────────
        pr_title = f"feat(glue): Add Glue job {job_key}"
        # Pass the actual source_exists value (from GitHub check, not from state)
        pr_body  = self._build_pr_body(state, committed_files, source_exists_actual=source_exists)

        pr = _with_retry(
            lambda: repo.create_pull(
                title=pr_title,
                body=pr_body,
                head=branch_name,
                base=self._base_branch,
            )
        )

        # ── 4. Labels (fail gracefully — labels may not exist in repo yet) ───
        try:
            labels = ["ai-generated", "terraform"]
            if environment:
                labels.append(f"env:{environment}")
            pr.add_to_labels(*labels)
        except GithubException as exc:
            logger.warning("Could not add labels to PR #%s: %s", pr.number, exc)

        # ── 5. Reviewers (fail gracefully) ────────────────────────────────────
        if self._reviewers:
            try:
                pr.create_review_request(reviewers=self._reviewers)
            except GithubException as exc:
                logger.warning(
                    "Could not assign reviewers to PR #%s: %s", pr.number, exc
                )

        return {
            "pr_url":        pr.html_url,
            "branch_name":   branch_name,
            "pr_number":     pr.number,
            "files_modified": committed_files,
        }

    # ── Scenario 1: existing source system ────────────────────────────────────

    def _commit_existing_system(
        self, repo, branch_name: str, state: dict, locals_path: str
    ) -> list[str]:
        """
        Read `{source}/locals.tf` from the base branch, insert the new
        job entry into the ``glue_jobs`` block, and commit the modified file to the
        PR branch.  glue.tf is NOT modified — its for_each handles new entries.
        """
        source_system = state.get("source_system", "")
        job_key       = state.get("job_key", "unknown")
        terraform_hcl = state.get("terraform_hcl", "")

        if not terraform_hcl:
            raise ValueError("state.terraform_hcl is empty — cannot insert job entry")

        # Use the actual locals_path discovered in the repository (may be under terraform/)
        # Read from base branch (authoritative content)
        base_file = self._get_file_content(repo, locals_path, self._base_branch)
        if base_file is None:
            raise ValueError(
                f"Could not read '{locals_path}' from branch '{self._base_branch}'. "
                "Verify the file exists in the repository and the branch name is correct."
            )

        current_content = base_file.decoded_content.decode("utf-8")

        # Insert the new job entry
        try:
            modified_content = _insert_into_glue_jobs(current_content, terraform_hcl)
        except ValueError as exc:
            raise ValueError(
                f"Failed to insert job entry into {locals_path}: {exc}\n\n"
                f"HCL block to insert:\n{terraform_hcl}"
            ) from exc

        commit_message = f"feat(glue): add {job_key} to {locals_path}"

        # Commit to PR branch (create if not present, update if branch already had a commit)
        self._create_or_update_file(
            repo, locals_path, modified_content, commit_message, branch_name
        )
        return [locals_path]

    # ── Scenario 2: new source system ─────────────────────────────────────────

    def _commit_new_system(
        self, repo, branch_name: str, state: dict
    ) -> list[str]:
        """
        Create `{source}/locals.tf` and `{source}/glue.tf`
        from scratch using the content generated by TerraformAgent.
        """
        source_system   = state.get("source_system", "")
        job_key         = state.get("job_key", "unknown")
        locals_tf_full  = state.get("locals_tf_full", "")
        glue_tf_content = state.get("glue_tf_content", "")

        if not locals_tf_full:
            raise ValueError(
                "state.locals_tf_full is empty — cannot create locals.tf for new "
                "source system. Ensure the generate_terraform step ran successfully."
            )

        committed: list[str] = []
        locals_path = f"{source_system}/locals.tf"
        glue_path   = f"{source_system}/glue.tf"

        self._create_or_update_file(
            repo, locals_path, locals_tf_full,
            f"feat(glue): create {locals_path} for {job_key}",
            branch_name,
        )
        committed.append(locals_path)

        if glue_tf_content:
            self._create_or_update_file(
                repo, glue_path, glue_tf_content,
                f"feat(glue): create {glue_path} (standard module block)",
                branch_name,
            )
            committed.append(glue_path)

        return committed

    # ── STEP 2.3: ONE COMMIT per PR (NEW) ─────────────────────────────────────

    def create_single_commit_and_pr(
        self,
        repo_name: str,
        target_branch: str,
        base_sha: str,
        tree_entries: list,  # List[{ path, content, mode }]
        branch_name: str,
        commit_message: str,
        pr_title: str,
        pr_body: str,
    ) -> dict:
        """
        STEP 2.3: Atomic operation creating exactly ONE commit and one PR.

        Enforces the Step 2.3 requirement: One PR = One Commit.

        Args:
            repo_name: GitHub repo (owner/repo format)
            target_branch: base branch name (e.g., 'main')
            base_sha: SHA to use as commit parent
            tree_entries: List of { path, content, mode } dicts for files
            branch_name: PR branch name (will be created/updated)
            commit_message: Commit message (user-editable)
            pr_title: PR title (user-editable)
            pr_body: PR description (user-editable)

        Returns:
            { commit_sha, pr_url, pr_number, branch_name }

        Raises:
            GitHubAPIError if any operation fails (divergence, auth, etc.)
        """
        repo = self._get_repo()

        # Step 1: Create blobs for all files
        blob_shas = {}
        try:
            for entry in tree_entries:
                path = entry["path"]
                content = entry["content"]
                # Some PyGithub versions return an object with a `.sha` attribute;
                # tests/mocks sometimes return an object with `.sha` as well.
                # Normalize to the SHA string so InputGitTreeElement receives a
                # plain string as expected by GitHub API.
                blob_obj = _with_retry(lambda c=content: repo.create_git_blob(c, "utf-8"))
                # Unwrap nested .sha attributes (mocks or API wrappers) until we
                # reach a plain string SHA when possible.
                blob_sha = blob_obj if isinstance(blob_obj, str) else getattr(blob_obj, "sha", blob_obj)
                unwrap_attempts = 0
                while not isinstance(blob_sha, str) and hasattr(blob_sha, "sha") and unwrap_attempts < 5:
                    blob_sha = getattr(blob_sha, "sha")
                    unwrap_attempts += 1
                # Final fallback: coerce to str to avoid passing MagicMock into
                # InputGitTreeElement (tests expect a str SHA).
                if not isinstance(blob_sha, str):
                    blob_sha = str(blob_sha)
                blob_shas[path] = blob_sha
                logger.info(f"Created blob for {path}: {blob_sha}")
        except GithubException as exc:
            raise ValueError(f"Failed to create blob: {exc}") from exc

        # Step 2: Create tree with all blobs
        tree_input = []
        for entry in tree_entries:
            path = entry["path"]
            mode = entry.get("mode", "100644")  # Default to file
            tree_input.append(
                InputGitTreeElement(
                    path=path,
                    mode=mode,
                    type="blob",
                    sha=blob_shas[path],
                )
            )

        try:
            tree = _with_retry(lambda: repo.create_git_tree(tree_input))
            logger.info(f"Created tree: {tree.sha}")
        except GithubException as exc:
            raise ValueError(f"Failed to create tree: {exc}") from exc

        # Step 3: Create single commit with parent = base_sha
        try:
            commit = _with_retry(
                lambda: repo.create_git_commit(
                    message=commit_message,
                    tree=tree,
                    parents=[repo.get_git_commit(base_sha)],
                )
            )
            logger.info(f"Created commit: {commit.sha} (parent: {base_sha})")
        except GithubException as exc:
            raise ValueError(f"Failed to create commit: {exc}") from exc

        # Step 4: Update or create branch ref to point to the new commit
        try:
            try:
                ref = _with_retry(lambda: repo.get_git_ref(f"heads/{branch_name}"))
                # Branch exists — update it
                _with_retry(lambda: ref.edit(commit.sha))
                logger.info(f"Updated branch {branch_name} to {commit.sha}")
            except GithubException as exc:
                if exc.status == 422:
                    # Branch doesn't exist — create it
                    _with_retry(
                        lambda: repo.create_git_ref(
                            f"refs/heads/{branch_name}", commit.sha
                        )
                    )
                    logger.info(f"Created branch {branch_name} at {commit.sha}")
                else:
                    raise
        except GithubException as exc:
            raise ValueError(f"Failed to update branch ref: {exc}") from exc

        # Step 5: Create PR
        try:
            pr = _with_retry(
                lambda: repo.create_pull(
                    title=pr_title,
                    body=pr_body,
                    head=branch_name,
                    base=target_branch,
                )
            )
            logger.info(f"Created PR #{pr.number}: {pr.html_url}")
        except GithubException as exc:
            raise ValueError(f"Failed to create PR: {exc}") from exc

        # Step 6: Add labels (fail-gracefully)
        try:
            labels = ["ai-generated", "terraform", "draft-workspace"]
            pr.add_to_labels(*labels)
        except GithubException:
            logger.warning(f"Could not add labels to PR #{pr.number}")

        # Step 7: Add reviewers (fail-gracefully)
        if self._reviewers:
            try:
                pr.create_review_request(reviewers=self._reviewers)
            except GithubException:
                logger.warning(f"Could not add reviewers to PR #{pr.number}")

        return {
            "commit_sha": commit.sha,
            "pr_url": pr.html_url,
            "pr_number": pr.number,
            "branch_name": branch_name,
        }

    def get_current_head_sha(self, branch_name: str = None) -> str:
        """
        Get current HEAD SHA for the target branch (default: base_branch).
        Used to detect divergence.
        """
        if branch_name is None:
            branch_name = self._base_branch

        try:
            # Prefer get_git_ref(...) when available on the repo (mocks/tests may
            # configure that). Fall back to get_branch(...).
            repo = self._get_repo()
            try:
                ref = _with_retry(lambda: repo.get_git_ref(f"heads/{branch_name}"))
                sha = getattr(getattr(ref, 'object', ref), 'sha', None) or getattr(getattr(ref, 'commit', ref), 'sha', None)
                if sha:
                    logger.info(f"Current HEAD (ref) on {branch_name}: {sha}")
                    return sha
            except GithubException:
                # Fall back to branch API
                pass

            ref = _with_retry(lambda: repo.get_branch(branch_name))
            sha = getattr(getattr(ref, 'commit', ref), 'sha', None)
            if sha:
                logger.info(f"Current HEAD (ref) on {branch_name}: {sha}")
                return sha
            raise GithubException("Could not resolve HEAD SHA")
        except GithubException as exc:
            raise ValueError(f"Could not fetch HEAD SHA for {branch_name}: {exc}") from exc

    def preview_tree_diff(
        self,
        base_sha: str,
        tree_entries: list,
    ) -> dict:
        """
        Compute a diff between base_sha and the proposed tree_entries
        WITHOUT creating a commit or writing to GitHub.

        Used for preview screen before PR creation.

        Returns:
            {
                "base_sha": base_sha,
                "tree_entries_count": len(tree_entries),
                "files": [
                    { "path": path, "status": "added"|"modified", "size": size }
                ],
                "total_additions": sum,
                "total_deletions": sum,
            }
        """
        base_tree = {}

        # Fetch base tree from GitHub
        try:
            repo = self._get_repo()
            base_commit = _with_retry(lambda: repo.get_git_commit(base_sha))
            base_tree_obj = base_commit.tree

            # Recursively load all files in base tree
            def load_tree_files(tree_obj, prefix=""):
                result = {}
                for item in tree_obj.tree:
                    full_path = f"{prefix}{item.path}" if prefix else item.path
                    if item.type == "blob":
                        result[full_path] = {
                            "sha": item.sha,
                            "size": item.size,
                            "type": "file",
                        }
                    elif item.type == "tree":
                        # For simplicity, don't recurse into subdirectories
                        # Just track the tree
                        result[full_path + "/"] = {
                            "sha": item.sha,
                            "type": "tree",
                        }
                return result

            base_tree = load_tree_files(base_tree_obj)
        except GithubException as exc:
            logger.warning(f"Could not load base tree {base_sha}: {exc}")
            base_tree = {}

        # Compare new tree_entries to base_tree
        files_diff = []
        total_additions = 0
        total_deletions = 0

        for entry in tree_entries:
            path = entry["path"]
            content = entry["content"]
            size = len(content.encode("utf-8"))

            if path in base_tree:
                status = "modified"
                # Rough estimate: count line changes
                # For preview, just count size delta
                old_size = base_tree[path].get("size", 0)
                total_additions += max(0, size - old_size)
                total_deletions += max(0, old_size - size)
            else:
                status = "added"
                total_additions += size

            files_diff.append({
                "path": path,
                "status": status,
                "size": size,
            })

        return {
            "base_sha": base_sha,
            "tree_entries_count": len(tree_entries),
            "files": files_diff,
            "total_additions": total_additions,
            "total_deletions": total_deletions,
        }

    # ── File helpers ──────────────────────────────────────────────────────────

    def _create_or_update_file(
        self,
        repo,
        path: str,
        content: str,
        message: str,
        branch: str,
    ) -> None:
        """Create or update a single file on the given branch."""
        existing = self._get_file_content(repo, path, branch)
        if existing:
            _with_retry(
                lambda: repo.update_file(
                    path=path,
                    message=message,
                    content=content,
                    sha=existing.sha,
                    branch=branch,
                )
            )
        else:
            _with_retry(
                lambda: repo.create_file(
                    path=path,
                    message=message,
                    content=content,
                    branch=branch,
                )
            )

    def _get_file_content(self, repo, path: str, branch: str):
        """Return the ContentFile object for *path* on *branch*, or None."""
        try:
            return repo.get_contents(path, ref=branch)
        except GithubException:
            return None

    # ── PR body ───────────────────────────────────────────────────────────────

    def _build_pr_body(self, state: dict, committed_files: list[str], source_exists_actual: bool = None) -> str:
        """Compose a detailed PR description including the generated HCL.
        
        Args:
            source_exists_actual: If provided, use this value instead of state's source_system_exists.
                                 This represents the ACTUAL GitHub repository state.
        """
        job_key        = state.get("job_key", "")
        topic          = state.get("topic", "")
        source_system  = state.get("source_system", "")
        schema_grain   = state.get("schema_grain", "")
        # Use actual GitHub state if provided, otherwise fall back to state
        source_exists  = source_exists_actual if source_exists_actual is not None else state.get("source_system_exists", True)
        worker_type    = state.get("worker_type", "G.1X")
        num_workers    = state.get("number_of_workers", 2)
        environment    = state.get("environment", "")
        terraform_hcl  = state.get("terraform_hcl", "")

        status_badge = (
            "✅ Existing source system"
            if source_exists
            else "⚠️ **New source system** — folder and both Terraform files created"
        )
        files_md = "\n".join(f"- `{f}`" for f in committed_files)

        return f"""## 🚀 New Glue Job: `{job_key}`

> **Created by:** MIF Glue Job Agent (AI-assisted Terraform generation)

| Field | Value |
|---|---|
| Kafka Topic | `{topic}` |
| Environment | `{environment}` |
| Source System | `{source_system}` — {status_badge} |
| Schema Grain | `{schema_grain}` |
| Workers | {num_workers} × {worker_type} |

### Files Modified

{files_md}

### Generated HCL

```hcl
{terraform_hcl}
```

---

> ⚠️ **Terraform Plan Required** — please run `terraform plan` in the affected \
directory before merging.
> This PR was auto-generated by the MIF Glue Job Agent. Review the HCL carefully \
before approving.
"""


